Swagger
wolox-training/lum-java pull request #6
Opened 2020-02-17 12:59 UTC by lmiotti

### Summary
Swagger added to project

### Trello Card
https://trello.com/c/Oju9eg57/40-swagger

2020-02-17 17:24 UTC, rabinovichm requested changes

2020-02-17 17:24 UTC, rabinovichm commented on training/src/main/java/wolox/training/controllers/BookController.java
> +    @ApiOperation(value = "Giving a book, creates a book", response = Book.class)
Add the possible status codes that can be returned

2020-02-17 17:24 UTC, rabinovichm commented on training/src/main/java/wolox/training/controllers/BookController.java
> +        @ApiParam(value = "Book object") @RequestBody Book book) {
Considering that swagger is the first approach that a person will have with our api, the information it provides should be as descriptive as possible. "_Book object_" doesn't say too much, maybe "_Book to be created_" is a little bit more expressive. Consider this for all the api params in each endpoint.

2020-02-17 17:24 UTC, rabinovichm commented on training/src/main/java/wolox/training/controllers/BookController.java
> +        @ApiParam(value = "Book object", required = true) @RequestBody Book book,
Same here
And it should be "_given book_" instead of "_give book_" on the api operation value :yum:

2020-02-17 17:24 UTC, rabinovichm commented on training/src/main/java/wolox/training/controllers/BookController.java
> +    @ApiOperation(value = "Giving an author, returns a book")
Add the possible status codes that can be returned

2020-02-17 17:24 UTC, rabinovichm commented on training/src/main/java/wolox/training/controllers/BookController.java
> +    @ApiOperation(value = "Giving an id, returns a book", response = Book.class)
Add the possible status codes that can be returned

2020-02-17 17:24 UTC, rabinovichm commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    @ApiOperation(value = "Giving a user and username, updates given user", response = Users.class)
Add the possible status codes that can be returned

2020-02-17 17:24 UTC, rabinovichm commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    @ApiOperation(value = "Giving an id, deletes selected user")
Add the possible status codes that can be returned

2020-02-17 17:24 UTC, rabinovichm commented on training/src/main/java/wolox/training/controllers/UserController.java
> +    @ApiOperation(value = "Giving an id and book, ads that book to user")
Add the possible status codes that can be returned

2020-02-17 22:47 UTC, rabinovichm approved these changes

2020-02-18 16:20 UTC, darkBasic666 approved these changes

2020-02-18 17:18 UTC, merged