Setters validations
wolox-training/lum-java pull request #7
Opened 2020-02-17 17:14 UTC by lmiotti

### Summary
Added preconditions to check if User or Book is null, and if ID is positive for both cases.

### Trello Card
https://trello.com/c/khWxYGxs/29-agregar-validaci%C3%B3n-de-precondiciones-a-los-setters

2020-02-17 17:31 UTC, rabinovichm requested changes
The controllers should not contain any business logic. The validations should be done in the setters of each model. In order to make these validations check the models' restrictions specified on the Book model and User model trello cards.

2020-02-18 20:23 UTC, leandrocostawolox requested changes
Good! Just fix some merge conflict that you commited :)

2020-02-18 20:23 UTC, leandrocostawolox commented on training/src/main/java/wolox/training/controllers/BookController.java
> +<<<<<<< HEAD
You commited this file without solve the conflict (There are some `<<<<< HEAD` and `>>>>>> master`

2020-02-18 20:57 UTC, leandrocostawolox approved these changes
Good job!
Just to let you know, you can have a ErrorMessages class inside a utils package. This class could be final (to avoid inheritance) and have a static method which receives a String (called fieldName for example) and returns the custom messages, so you centralized there the message that mustn't be null

2020-02-19 15:14 UTC, darkBasic666 approved these changes

2020-02-19 15:14 UTC, darkBasic666 commented on training/src/main/java/wolox/training/controllers/BookController.java
> +<<<<<<< HEAD
marge conflicts

2020-02-19 19:20 UTC, merged